[build]
  command = "npm run build:netlify"
  publish = "dist/web-app"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=8192"
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Redirect root to login page (since app uses hash routing)
[[redirects]]
  from = "/"
  to = "/#/login"
  status = 302

# SPA redirect - all routes should serve index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 