[build]
  command = "npm run build:netlify"
  publish = "dist/web-app/browser"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=8192"
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# For Angular apps with hash routing, we only need to serve index.html for all routes
# The Angular router will handle the actual routing on the client side
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 